### PR TITLE
Clean up the specs

### PR DESCRIPTION
**Pull request by alexbuzzbee**
I've made the specs more consistent and more clear, and I've also proofread them.

I think I've managed not to change the meaning of any of the specs more than absolutely necessary to make them consistant.

`<rant>`

I think `if` and logic operations should treat the same things as true and false. I'm fine with `True` being false and vice versa (even if it's not really in line with any of our inspiration languages, even if we do throw in JavaScript), but conditionals and logic operations should be consistant with each other. The goal is to make a horrible *combination* of Python, PHP, C++, and C#, not a horrible language that happens to have bits from those languages.

`</rant>`

### CODE REVIEW

**Comment by alexbuzzbee** [comment]
`<rantaddendum>`

Possible solution: rename `if` to something different, like `ifnot`.

`<rantaddendum>`

**Comment by Boscillator** [comment]
`<rant_reply>`
I agree, we are getting too silly. We're trying to make a serous (...ly bad) language, not one of those esoteric languages.
If should be renamed to `unless`
`</rant_reply>`

Also, thank you for formatting those specs. I particularly like that bottom of stack is falsey instead of throwing an error.

ps.
Can somebody make me a member of the `PyHP-pph` organization.

**Comment by alexbuzzbee** [comment]
You aren't a member? *oops*!

I'll fix that ASAP.

**Comment by alexbuzzbee** [comment]
Okay, I can't make you a member. @as-com, please invite @Boscillator.

**Comment by as-com** [comment]
@alexbuzzbee Done. Does he belong in the reddit moderator group?

**Comment by Boscillator** [comment]
Thank you so much. And no, I don't belong to the Reddit moderators group. (I'm /u/boscillator)

**Comment by alexbuzzbee** [comment]
Don't merge yet, please. I'm going to switch it to RFC 2119 language.

**Comment by alexbuzzbee** [comment]
Now ready to merge once someone else signs off on it.

**Pull request merged**
